FULL_TYPE = 'FULL'
SHORT_TYPE = 'SHORT'
STATUS_TYPE = 'STATUS'
WARNING_TYPE = 'WARNING'
WARN_TYPE = 'WARN'
ERROR_TYPE = 'ERROR'
ALL_TYPE = [FULL_TYPE, SHORT_TYPE, STATUS_TYPE, WARNING_TYPE, WARN_TYPE, ERROR_TYPE]
